version: '3'
services:
  app:
    build: .
    container_name: blog_app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: blog_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.dnt
    ports:
      - 33061:3306